stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: 'beanstalk-bluegreen:$(SourceBranchName)'

    - task: ECRPushImage@1
      displayName: Push image
      inputs:
        awsCredentials: 'sharedService-InfraDeployAccess'
        regionName: 'ap-southeast-2'
        sourceImageName: 'beanstalk-bluegreen'
        sourceImageTag: '$(SourceBranchName)'
        pushTag: '$(SourceBranchName)'
        repositoryName: 'beanstalk-bluegreen'
        outputVariable: ecrImageUrl